#!/usr/bin/env bash

#Setting up a VETH pair to communicate
ip netns add client #Add a network namespace named client
ip link add veth0 type veth peer name eth0 #Set up a VETH, for the namespace, and a ETH, on VM, connected together
ip link set dev eth0 netns client up #Set etho0, which is in the namespace, to up
ip link set dev veth0 up #Set veth to up

#Giving the pair IP's
ip addr add 192.168.1.1/30 dev veth0 #/30 b/c need the 2 end bits for 1 & 2 but rest are same
ip -n client addr add 192.168.1.2/30 dev eth0 #Give eth0 an IP by entering client without going in there

#Forward traffic from client to bridge to tunnel
sysctl net.ipv4.ip_forward=1 #Allow IP forwarding
ip route add 192.168.1.0/30 dev veth0 proto kernel scope link src 192.168.1.1 table 66 #Add IP range to VETH, install automatically by kernel, it's gonna look for a link srced at 1.1 and use rules from table 66
ip rule add from 192.168.1.0/30 table 66 #If it's from IP range use table 66 rules
ip -n client route add 0/0 via 192.168.1.1 #Route all client traffic via the eth connection

